title: Trident Walkthrough
description: A guide to some specific Voron Tridents
theme: just-the-docs

url: https://intervade.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
